// TODO: MODULE STATUS: done, pending testing

// BUG: ensure doesn't throw an error when the list doesn't exist, therefore the catch never executes. Coded around it temporarily but is this a bigger issue, shouldn't errors be thrown?
